/*
 Navicat Premium Data Transfer

 Source Server         : Project
 Source Server Type    : Oracle
 Source Server Version : 190000 (Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production)
 Source Host           : 0.0.0.0:1521
 Source Schema         : PROJECT

 Target Server Type    : Oracle
 Target Server Version : 190000 (Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production)
 File Encoding         : 65001

 Date: 10/09/2023 23:46:26
*/


-- ----------------------------
-- Table structure for OFFER
-- ----------------------------
DROP TABLE "PROJECT"."OFFER";

CREATE TABLE "PROJECT"."OFFER" (
  "OFFERID" NUMBER(10, 0) VISIBLE NOT NULL,
  "MESSAGE" VARCHAR2(500 BYTE) VISIBLE,
  "BOOKCONDITIONPHOTO" VARCHAR2(500 BYTE) VISIBLE NOT NULL,
  "USEREMAILID" VARCHAR2(50 BYTE) VISIBLE NOT NULL,
  "ISBN" VARCHAR2(50 BYTE) VISIBLE NOT NULL,
  "TIME" TIMESTAMP(6) VISIBLE,
  "STATUS" VARCHAR2(10 BYTE) VISIBLE,
  "BOOKCONDITIONPHOTO1" VARCHAR2(500 BYTE) VISIBLE,
  "BOOKCONDITIONPHOTO2" VARCHAR2(500 BYTE) VISIBLE,
  "BOOKCONDITIONPHOTO3" VARCHAR2(500 BYTE) VISIBLE,
  "BOOKCONDITIONPHOTO4" VARCHAR2(500 BYTE) VISIBLE
) LOGGING NOCOMPRESS PCTFREE 10 INITRANS 1 STORAGE (
  INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 BUFFER_POOL DEFAULT
) PARALLEL 1 NOCACHE DISABLE ROW MOVEMENT;

-- ----------------------------
-- Primary Key structure for table OFFER
-- ----------------------------
ALTER TABLE "PROJECT"."OFFER" ADD CONSTRAINT "SYS_C008174" PRIMARY KEY ("OFFERID");

-- ----------------------------
-- Checks structure for table OFFER
-- ----------------------------
ALTER TABLE "PROJECT"."OFFER" ADD CONSTRAINT "SYS_C008170" CHECK ("OFFERID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

ALTER TABLE "PROJECT"."OFFER" ADD CONSTRAINT "SYS_C008171" CHECK ("BOOKCONDITIONPHOTO" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

ALTER TABLE "PROJECT"."OFFER" ADD CONSTRAINT "SYS_C008172" CHECK ("USEREMAILID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

ALTER TABLE "PROJECT"."OFFER" ADD CONSTRAINT "SYS_C008173" CHECK ("ISBN" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Foreign Keys structure for table OFFER
-- ----------------------------
ALTER TABLE "PROJECT"."OFFER" ADD CONSTRAINT "SYS_C008175" FOREIGN KEY ("USEREMAILID") REFERENCES "PROJECT"."BOOKFRIEND" ("EMAILID") ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

ALTER TABLE "PROJECT"."OFFER" ADD CONSTRAINT "SYS_C008176" FOREIGN KEY ("ISBN") REFERENCES "PROJECT"."BOOK" ("ISBN") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;