CREATE TABLE AUTHOR (
	name VARCHAR(100) NOT NULL,
	bornOn NUMERIC(4, 0) NOT NULL,
	diedOn NUMERIC(4, 0),
	type VARCHAR(50),
	nationality VARCHAR(20),
	PRIMARY KEY (name, bornOn)
);
CREATE TABLE ADDRESS (
	latitude NUMERIC(10, 7) NOT NULL,
	longitude NUMERIC(10, 7) NOT NULL,
	PRIMARY KEY (latitude, longitude)
);
CREATE TABLE PUBLISHER (
	name VARCHAR(100) NOT NULL,
	ADDRESS VARCHAR(200),
	website VARCHAR(50),
	email VARCHAR(50),
	contactNo NUMERIC(15, 0),
	PRIMARY KEY (name)
);
CREATE TABLE USERMAN (
	emailID VARCHAR(50) NOT NULL,
	contactNo1 NUMERIC(15, 0) NOT NULL,
	contactNo2 NUMERIC(15, 0),
	firstName VARCHAR(50) NOT NULL,
	dateOfBirth DATE NOT NULL,
	gender VARCHAR(10) NOT NULL,
	lastName VARCHAR(50) NOT NULL,
	latitude NUMERIC(10, 7) NOT NULL,
	longitude NUMERIC(10, 7) NOT NULL,
	PRIMARY KEY (emailID),
	FOREIGN KEY (latitude, longitude) REFERENCES ADDRESS(latitude, longitude)
);
CREATE TABLE DELIVARYMAN (
	delivaryManID NUMERIC(10, 0) NOT NULL,
	emailID VARCHAR(50) NOT NULL,
	PRIMARY KEY (emailID),
	FOREIGN KEY (emailID) REFERENCES USERMAN(emailID),
	UNIQUE (delivaryManID)
);
CREATE TABLE BOOKFRIEND (
	bookFriendID NUMERIC(10, 0) NOT NULL,
	emailID VARCHAR(50) NOT NULL,
	PRIMARY KEY (emailID),
	FOREIGN KEY (emailID) REFERENCES USERMAN(emailID),
	UNIQUE (bookFriendID)
);
CREATE TABLE NOTIFICATION (
	time TIMESTAMP NOT NULL,
	message VARCHAR(500),
	userEmailID VARCHAR(50) NOT NULL,
	PRIMARY KEY (time),
	FOREIGN KEY (userEmailID) REFERENCES USERMAN(emailID)
);
CREATE TABLE BOOK (
	ISBN VARCHAR(50) NOT NULL,
	title VARCHAR(100) NOT NULL,
	pageCount NUMERIC(5, 0),
	language VARCHAR(20) NOT NULL,
	genre VARCHAR(50) NOT NULL,
	publishYear NUMERIC(4, 0),
	price NUMERIC(5, 2),
	coverPhoto VARCHAR(100),
	publisherName VARCHAR(100),
	PRIMARY KEY (ISBN),
	FOREIGN KEY (publisherName) REFERENCES PUBLISHER(name)
);
CREATE TABLE EXCHANGEOFFER (
	exchangeID NUMERIC(10, 0) NOT NULL,
	processStartDate DATE,
	exchangeCompletionDate DATE,
	delivaryManEmailID VARCHAR(50),
	PRIMARY KEY (exchangeID),
	FOREIGN KEY (delivaryManEmailID) REFERENCES DELIVARYMAN(emailID)
);
CREATE TABLE OFFER (
	declareDate DATE NOT NULL,
	offerID NUMERIC(10, 0) NOT NULL,
	message VARCHAR(500),
	bookConditionPhoto VARCHAR(100) NOT NULL,
	userEmailID VARCHAR(50) NOT NULL,
	ISBN VARCHAR(50) NOT NULL,
	exchangeID NUMERIC(10, 0),
	PRIMARY KEY (offerID),
	FOREIGN KEY (userEmailID) REFERENCES BOOKFRIEND(emailID),
	FOREIGN KEY (ISBN) REFERENCES BOOK(ISBN),
	FOREIGN KEY (exchangeID) REFERENCES EXCHANGEOFFER(exchangeID)
);
CREATE TABLE REVIEW (
	messageForUs VARCHAR(500),
	dateOfReview DATE NOT NULL,
	rateUs NUMERIC(1, 0) NOT NULL,
	reviewID NUMERIC(10, 0) NOT NULL,
	emailID VARCHAR(50) NOT NULL,
	PRIMARY KEY (reviewID),
	FOREIGN KEY (emailID) REFERENCES USERMAN(emailID)
);
CREATE TABLE WRITTENBY (
	ISBN VARCHAR(50) NOT NULL,
	name VARCHAR(100) NOT NULL,
	bornOn NUMERIC(4, 0) NOT NULL,
	PRIMARY KEY (ISBN, name, bornOn),
	FOREIGN KEY (ISBN) REFERENCES BOOK(ISBN),
	FOREIGN KEY (name, bornOn) REFERENCES AUTHOR(name, bornON)
);