BEGIN CREATE_OFFER(:MESSAGE, :PHOTO, :ID, :ISBN, :MSG, :PHOTO1, :PHOTO2, :PHOTO3, :PHOTO4);
END;
DECLARE
    MS1 VARCHAR2(50);
    MS2 VARCHAR2(50);
    MS3 VARCHAR2(50);
BEGIN
    ADD_PUBLISHER(:PUBLISHER, NULL, MS1);
    ADD_AUTHOR(:AUTHOR, NULL, NULL, :AUTHORTYPE, NULL, MS2);
    ADD_BOOK(:ISBN, :TITLE, :PAGE, :LAN, :PUBLISHED, :PRICE, :PUBLISHER, :SUMMARY, :GENRE, :MSG);
    ADD_BOOK_WRITER(:ISBN, :AUTHOR, MS3);
END;
BEGIN DECLINE_OFFER(:ID, :MSG);
END;
BEGIN DELETE_OFFER(:OFFERID, :MSG);
END;
DECLARE BEGIN CREATE_NOTIFICATION1 (:USERID, :OFFERID, :MSG);
END;
DECLARE
    MS1 VARCHAR2(50);
    MS2 VARCHAR2(50);
    MS3 VARCHAR2(50);
    MS4 VARCHAR2(50);
BEGIN
    ACCEPT_OFFER_FINALLY (:OFFERID1, MS1);
    ACCEPT_OFFER_FINALLY (:OFFERID2, MS2);
    IF MS1 = 'CREATED' AND MS2 = 'CREATED' THEN
        DISABLE_NOTIFICATION (:NOTIID, MS3);
        CREATE_EXCHANGE_OFFER(:OFFERID1, :OFFERID2, :MSG);
    END IF;
END;
BEGIN SIGNUP(:EMAIL, DBMS_CRYPTO.ENCRYPT(UTL_RAW.CAST_TO_RAW(:PASSWORD), 4353, UTL_RAW.CAST_TO_RAW ('MyBibliophileFriend')), :FIRSTNAME, TO_DATE(:DOB, 'YYYY-MM-DD'), :GENDER, :LASTNAME, :LATITUDE, :LONGITUDE, :PHN1, :PHN2, :MSG1);
ADD_TO_BOOKFRIEND(:EMAIL, :MSG2);
END;
BEGIN UPDATE_PASS (:EMAIL, :CURRPASS, :NEWPASS, :MSG);
END;
DECLARE
    MSG1 VARCHAR2(20);
BEGIN
    CONFIRM_DELIVARY(:EID, :DELID, :FEE, :MSG);
    DISABLE_EXCHANGEOFFER(:EID, MSG1);
END;
BEGIN SIGNUP(:EMAIL, DBMS_CRYPTO.ENCRYPT(UTL_RAW.CAST_TO_RAW(:PASSWORD), 4353, UTL_RAW.CAST_TO_RAW ('MyBibliophileFriend')), :FIRSTNAME, TO_DATE(:DOB, 'YYYY-MM-DD'), :GENDER, :LASTNAME, :LATITUDE, :LONGITUDE, :PHN1, :PHN2, :MSG1);
ADD_TO_DELIVARYMAN(:EMAIL, :MSG2);
END;
